### ISSUE TITLE
make select distinguishable from line highlight and generally easy to see

### ISSUE THREAD

**Issue by effinsky** [kaiuri/nvim-juliana#20]
Love this theme. But currently line highlight and visual mode selections have the same color and generally selections are really hard to spot. Would be cool to get that improved. Thanks in advance!

visual line  mode:
<img width="986" alt="Screenshot 2023-04-05 at 09 31 37" src="https://user-images.githubusercontent.com/54535543/230020035-4575b17a-e906-43e4-824e-0c7f4a500bd8.png">

line highlight feature:
<img width="1185" alt="Screenshot 2023-04-05 at 09 31 32" src="https://user-images.githubusercontent.com/54535543/230019947-f2c9746b-51ef-4889-9199-f7097baeb98e.png">

**Comment by kaiuri** [comment]
Here CursorLine highlighting is hidden whenever `vim.o.cursorline = true` and I start a visual selection.
 
```vimdoc
							*hl-CursorLine*
CursorLine	Screen-line at the cursor, when 'cursorline' is set.
		Low-priority if foreground (ctermfg OR guifg) is not set.
```

Since this theme sets neither `ctermfg` nor `guifg` for `CursorLine` it could be an issue with your configuration.

**Comment by effinsky** [comment]
that's all good. I'm saying the visual selection is hard to spot. here are a few examples for comparison of cursor line and vis selection:
<img width="685" alt="Screenshot 2023-04-07 at 21 46 44" src="https://user-images.githubusercontent.com/54535543/230668542-df8911be-cc66-47a8-b682-144b824ff296.png">
<img width="732" alt="Screenshot 2023-04-07 at 21 46 49" src="https://user-images.githubusercontent.com/54535543/230668545-414cbc91-80c4-4df8-9d28-cccab38634ea.png">
<img width="635" alt="Screenshot 2023-04-07 at 21 47 02" src="https://user-images.githubusercontent.com/54535543/230668546-e8298f77-457f-46dc-b66f-3a9e1c538b70.png">
<img width="673" alt="Screenshot 2023-04-07 at 21 47 08" src="https://user-images.githubusercontent.com/54535543/230668548-88ebdcd5-ed39-4c0d-86f2-f830ae4823c6.png">
<img width="718" alt="Screenshot 2023-04-07 at 21 47 18" src="https://user-images.githubusercontent.com/54535543/230668549-02181f71-2112-48c6-a9ec-d6ff9ea3f6d6.png">
<img width="657" alt="Screenshot 2023-04-07 at 21 47 23" src="https://user-images.githubusercontent.com/54535543/230668550-abb5a7f0-0aa0-421b-a26c-4f90d38971b2.png">
<img width="658" alt="Screenshot 2023-04-07 at 21 47 35" src="https://user-images.githubusercontent.com/54535543/230668552-69d79d4c-54bf-4669-8dc9-b42e009bc6fe.png">
<img width="738" alt="Screenshot 2023-04-07 at 21 47 44" src="https://user-images.githubusercontent.com/54535543/230668554-7426b682-4a5b-4cdc-b325-132d7d027b1c.png">

And Juliana:
<img width="703" alt="Screenshot 2023-04-07 at 21 49 27" src="https://user-images.githubusercontent.com/54535543/230668729-f17b7cd4-ae7d-46eb-88ef-8b244016e394.png">
<img width="675" alt="Screenshot 2023-04-07 at 21 49 32" src="https://user-images.githubusercontent.com/54535543/230668731-511b2dac-2505-43ba-8a4f-8f0c852000b4.png">

Since you're grabbing the theme from Sublime's Mariana, maybe use the same selection color they do? I realize they use the same color for "line highlight" but that's clearer there since it's gutter highlight only, at least by default:

<img width="324" alt="Screenshot 2023-04-07 at 21 52 57" src="https://user-images.githubusercontent.com/54535543/230669294-8c413bcf-09d2-47d3-b370-2d41c38d92a0.png">

Of course, if you like it better the way it is, keep it and I'll just fork it and change it for myself. I'm just trying to help.

**Comment by kaiuri** [comment]
@effinsky you could open a pull request or post this `line highlight`'s hex color here. All help is welcome.

**Comment by kaiuri** [comment]
@effinsky you could open a pull request or post that `line highlight`'s hex color here. All help is welcome.

**Comment by effinsky** [comment]
sure, on it.
