### ISSUE TITLE
Report error messages

### ISSUE THREAD

**Issue by tan-wei** [kaiuri/nvim-juliana#8]
It looks awesome. But in my neovim-nightly (v0.8.0-dev+532-g60604d6a9)，it fails to launch:

![图片](https://user-images.githubusercontent.com/28227509/176987096-fb23d13a-0a74-4451-8dfd-934bc702e52b.png)

**Comment by kaiuri** [comment]
Neovim did a new [breaking change](https://github.com/neovim/neovim/issues/14090#issuecomment-1170955189), `underdot` is now `underdotted`, `underdash`, `underdashed`. I've [fixed](https://github.com/kaiuri/nvim-mariana/commit/c758cce56780b9338fc6516db2c7cf516a7bfca1) it already. Update the colorscheme and it'll work again.

Thanks for the compliment.

**Comment by tan-wei** [comment]
Got it. I'll try it now.

**Comment by tan-wei** [comment]
Yep, seems OK now, thanks.
